### ISSUE TITLE
summary bar display issue in large screens

### ISSUE THREAD

**Issue by laholstege** [ucdavis/tacos#39]
![image](https://user-images.githubusercontent.com/27025973/39215090-90a500d6-47cb-11e8-96da-24ee50b50884.png)
summary bar background isnt filled out like header is. part of the problem is that it should be "header_bleed" not "header-bleed" in Summary.tsx, but it still doesn't fix the problem. 

![image](https://user-images.githubusercontent.com/27025973/39215189-dbfc4814-47cb-11e8-8508-06a8cfdc3542.png)

**Comment by klanmiko** [comment]
@laholstege #47 got it. Removed header_bleed classes and made it a navbar.
